constant:
  qqNum: 195151847
  password:
  filterList:
    - 问题：学号姓名
    - 答案：



server:
  port: 80
logging:
  config: classpath:logback-spring.xml
  level:
    root: info


url:
  aliyunIp: http://139.224.204.81
